local_planner: "dwa_local_planner/DWAPlannerROS"
DWAPlannerROS:

  meter_scoring: true

  max_vel_x: 0.25
  min_vel_x: 0.05

  max_vel_y: 0.0
  min_vel_y: 0.0

  max_vel_theta: 1.0

  max_trans_vel: 0.5
  min_trans_vel: 0.1

  min_in_place_vel_theta: 0.4

  acc_lim_th: 0.6
  acc_lim_x: 1.0
  acc_lim_y: 0.0
  controller_frequency: 10.0

  holonomic_robot: true

  yaw_goal_tolerance: 0.2
  xy_goal_tolerance: 0.15
  sim_time: 4.0
  vx_samples: 10
  vy_samples: 5
  vtheta_samples: 30
  path_distance_bias: 32.0
  goal_distance_bias: 24.0
  occdist_scale: 0.5
  stop_time_buffer: 0.2
  oscillation_reset_dist: 0.05
  oscillation_reset_angle: 0.2
